# 优选阈值
preferred_thresholds: -1

theme_pack_list:
  forgot: 0 # G 公司
  gambl: 0 # 沙锤姐
  und: 0 # N 大锤
  faith: 0 # N 狗、蛇
  unconf: 0 # 烤冷面
  workshop: 0 # 工坊
  tearful: 0 # 妖精、蜈蚣、铜牛
  lake: 0 # 海盗
  dregs: 0 # 管家
  certain: 0 # 耐莉
  chick: 1 # 鸡包
  s.e.a: 0 # 寄居蟹
  miracle: 0 # 诺姆
  bullet: 0 # 齿轮
  cleaved: 0 # 电狼、伞妖、提灯
  penetra: 0 # 寄居蟹、棉花
  pierced: 0 # 寄居蟹、妖精、伞狐
  curshers: 0 # 铜牛、蛙蛙
  repression: 0 # 贝壳、诺姆、符人
  addict: 0 # 伞妖、符人
  seduct: 0 # 鸡
  dolen: 0 # 搬运、无头、苹果
  glutton: 0 # 提灯、妖精、贝壳
  cravi: 0 # 伞妖、迷失乘客
  gloom: 0 # 无头、蛙蛙
  subserv: 0 # 提灯、妖精、棉花
  nsignif: 0 # 蜈蚣、导游、迷失乘客
  judgment: 0 # 蛙蛙、玩具熊

  curshed: -1 # 挨打
  automated: -1 # 挨打
  outcast: -5 # 终末日历
  unloving: -5 # 芭芭雅嘎
  flowers: -5 # 山茶花
  abyss: -5 # 人皮预言者
  bones: -5 # 金笠
  time: -5 # 时间杀人魔
  warp: -5 # 卡塞蒂（净水器）
  violet: -5 # 请给我们爱（紫碑）
  dicers: -5 # 金笠
  wrath: -5 # 人皮预言者
  sloth: -5 # 洋流
  flood: -5 # 洋流
  vain: -5 # 金笠
  check: -5 # 霍恩海姆

theme_pack_list_hard:
  opening: 0 # 血魔
  procession: 0 # 血魔
  20: 0 # 诺姆
  seismic: 0 # 妖精
  extrenal: 0 # 寄居蟹、提灯、符人
  thunder: 0 # 蜈蚣、迷失乘客、电羊

  unchang: -5 # 山茶花
  evil: -5 # 亚哈
  heartb: -5 # 狼夫
  line: -5 #轨道
  repressed: -5 # 人皮
  unbound : -5 # 人皮
  tangling: -5 # 卡塞蒂
  inert: -5 # 洋流、山茶花、时间杀人魔
  excessive: -5 # 山茶花
  sunk: -5 # 狼夫
  pride: -5 # 亚哈、金笠
  pitiful: -5 # 狼夫
  haze: -5 # 人皮
  season: -5 # 人皮
  corpses: -5 # 卡塞蒂、狼夫
  might: -5 # 山茶花
  deluge: -5 # 洋流、山茶花
  poised: -5 # 亚哈、金笠、洋流

theme_pack_list_cn:
  遗忘: 0 # G 公司
  赌徒: 0 # 沙锤姐
  钉与锤: 0 # N 大锤
  信仰: 0 # N 狗、蛇
  无作为: 0 # 烤冷面
  工坊: 0 # 工坊
  落泪: 0 # 妖精、蜈蚣、铜牛
  湖的: 0 # 海盗
  宅邸: 0 # 管家
  某个世界: 0 # 耐莉
  地狱鸡: 1 # 鸡包
  海边: 0 # 寄居蟹
  奇迹: 0 # 诺姆
  句点: 0 # 齿轮
  当斩: 0 # 电狼、伞妖、提灯
  穿刺者: 0 # 寄居蟹、棉花
  当贯: 0 # 寄居蟹、妖精、伞狐
  粉碎者: 0 # 铜牛、蛙蛙
  情感压迫: 0 # 贝壳、诺姆、符人
  沉迷的: 0 # 伞妖、符人
  感情困惑: 0 # 鸡
  情感懒惰: 0 # 搬运、无头、苹果
  吞噬的: 0 # 提灯、妖精、贝壳
  情感饥渴: 0 # 伞妖、迷失乘客
  堕落的: 0 # 无头、蛙蛙
  情感屈从: 0 # 提灯、妖精、棉花
  寒微: 0 # 蜈蚣、导游、迷失乘客
  情感评判: 0 # 蛙蛙、玩具熊

  当碎: -1 # 挨打
  自动: -1 # 挨打
  无归属: -5 # 终末日历
  无慈悲: -5 # 芭芭雅嘎
  落花: -5 # 山茶花
  伏行深渊: -5 # 人皮预言者
  肉斩骨断: -5 # 金笠
  时间杀人: -5 # 时间杀人魔
  谋杀案: -5 # 卡塞蒂（净水器）
  紫罗兰: -5 # 请给我们爱（紫碑）
  斩切: -5 # 金笠
  压抑的: -5 # 人皮预言者
  虚张声势: -5 # 金笠
  沉溺者: -5 # 洋流
  空转的: -5 # 洋流
  体检: -5 # 霍恩海姆

theme_pack_list_hard_cn:
  重新开园: 0 # 血魔
  无尽的: 0 # 血魔
  奇迹复刻: 0 # 诺姆
  地震: 0 # 妖精
  破坏性: 0 # 寄居蟹、提灯、符人
  电闪雷鸣: 0 # 蜈蚣、迷失乘客、电羊

  定义为恶: -5 # 亚哈
  心意相悖: -5 # 狼夫
  号线: -5 #轨道
  解放的: -5 # 人皮
  捆缚的: -5 # 卡塞蒂
  停滞的: -5 # 洋流、山茶花、时间杀人魔
  漫溢的: -5 # 山茶花
  沉溺的: -5 # 狼夫
  自以为是: -5 # 亚哈、金笠
  凄惨的: -5 # 狼夫
  摇曳: -5 # 人皮
  盛火: -5 # 人皮
  尸山血海: -5 # 卡塞蒂、狼夫
  破竹之势: -5 # 山茶花
  沉沦泛滥: -5 # 洋流、山茶花
  循环呼吸: -5 # 亚哈、金笠、洋流
